package ElementosDeAnalisis;

import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author john
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla(String nroFactura, Date fechaActual, String condicionTributaria,
            long diasLectura, String domicilioFacturacion,
            Date fechaLecturaAnterior, float m3Consumidos,
            String nombreCliente, long nroCliente, int nroIDCatastral,
            float montoBasico, float costoImpresion, float impuesto, float iva, float total) {
        initComponents();
        this.nroFactura.setText(nroFactura);
        this.fechaActual.setText(String.valueOf(fechaActual));
        this.condicionTributaria.setText(condicionTributaria);
        this.costoImpresion.setText(String.valueOf(costoImpresion));
        this.diasLectura.setText(String.valueOf(diasLectura));
        this.domicilioFacturacion.setText(domicilioFacturacion);
        this.fechaLecturaAnterior.setText(String.valueOf(fechaLecturaAnterior));
        this.m3Consumidos.setText(String.valueOf(m3Consumidos));
        this.nombreCliente.setText(nombreCliente);
        this.nroCliente.setText(String.valueOf(nroCliente));
        this.nroIDCatastral.setText(String.valueOf(nroIDCatastral));
        this.montoBasico.setText(String.valueOf(montoBasico));
        this.impuesto.setText(String.valueOf(impuesto));
        this.iva.setText(String.valueOf(iva));
        this.subtotal.setText(String.valueOf(montoBasico + costoImpresion));
        this.total.setText(String.valueOf(total));

    }

    public Pantalla() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleL = new javax.swing.JLabel();
        nroFacturaL = new javax.swing.JLabel();
        fechaActualL = new javax.swing.JLabel();
        fechaActual = new javax.swing.JTextField();
        nroFactura = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        nroIDCatastralL = new javax.swing.JLabel();
        nroIDCatastral = new javax.swing.JTextField();
        nombreClienteL = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JTextField();
        nroClienteL = new javax.swing.JLabel();
        nroCliente = new javax.swing.JTextField();
        domicilioFacturacionL = new javax.swing.JLabel();
        domicilioFacturacion = new javax.swing.JTextField();
        condicionTributariaL = new javax.swing.JLabel();
        condicionTributaria = new javax.swing.JTextField();
        datosMedidorL = new javax.swing.JLabel();
        datosClienteL = new javax.swing.JLabel();
        marcaMedidorL = new javax.swing.JLabel();
        nroMedidorL = new javax.swing.JLabel();
        fechaInstalacionL = new javax.swing.JLabel();
        marcaMedidor = new javax.swing.JTextField();
        nroMedidor = new javax.swing.JTextField();
        fechaInstalacion = new javax.swing.JTextField();
        datosLecturaL = new javax.swing.JLabel();
        fechaLecturaAnteriorL = new javax.swing.JLabel();
        fechaLecturaActualL = new javax.swing.JLabel();
        diasLecturaL = new javax.swing.JLabel();
        m3ConsumidosL = new javax.swing.JLabel();
        fechaLecturaAnterior = new javax.swing.JTextField();
        fechaLecturaActual = new javax.swing.JTextField();
        diasLectura = new javax.swing.JTextField();
        m3Consumidos = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        conceptosL = new javax.swing.JLabel();
        montoBasicoL = new javax.swing.JLabel();
        costoImpresionL = new javax.swing.JLabel();
        subtotalL = new javax.swing.JLabel();
        impuestoL = new javax.swing.JLabel();
        IVAL = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        costoImpresion = new javax.swing.JTextField();
        montoBasico = new javax.swing.JTextField();
        subtotal = new javax.swing.JTextField();
        impuesto = new javax.swing.JTextField();
        iva = new javax.swing.JTextField();
        total = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleL.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        titleL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleL.setText("Empresa de AGUA SA");

        nroFacturaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nroFacturaL.setText("Nro Factura");

        fechaActualL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaActualL.setText("Fecha");

        fechaActual.setEditable(false);

        nroFactura.setEditable(false);

        nroIDCatastralL.setText("Identificador catastral propiedad");

        nroIDCatastral.setEditable(false);

        nombreClienteL.setText("Cliente");

        nombreCliente.setEditable(false);

        nroClienteL.setText("Numero cliente");

        nroCliente.setEditable(false);

        domicilioFacturacionL.setText("Domicilio de facturacion");

        domicilioFacturacion.setEditable(false);

        condicionTributariaL.setText("Condicion tributaria ante el IVA");

        condicionTributaria.setEditable(false);

        datosMedidorL.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        datosMedidorL.setText("Datos medidor");

        datosClienteL.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        datosClienteL.setText("Datos cliente");

        marcaMedidorL.setText("Marca");

        nroMedidorL.setText("Numero medidor");

        fechaInstalacionL.setText("Fecha instalacion");

        marcaMedidor.setEditable(false);

        nroMedidor.setEditable(false);

        fechaInstalacion.setEditable(false);

        datosLecturaL.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        datosLecturaL.setText("Datos lectura");

        fechaLecturaAnteriorL.setText("Fecha lectura anterior");

        fechaLecturaActualL.setText("Fecha lectura actual");

        diasLecturaL.setText("Dias de lectura");

        m3ConsumidosL.setText("M(cubicos) consumidos");

        fechaLecturaAnterior.setEditable(false);

        fechaLecturaActual.setEditable(false);

        diasLectura.setEditable(false);

        m3Consumidos.setEditable(false);

        conceptosL.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        conceptosL.setText("Conceptos");

        montoBasicoL.setText("Monto basico");

        costoImpresionL.setText("Costo impresion");

        subtotalL.setText("Subtotal");

        impuestoL.setText("Impuesto");

        IVAL.setText("IVA");

        jLabel6.setText("Total a facturar");

        costoImpresion.setEditable(false);

        montoBasico.setEditable(false);

        subtotal.setEditable(false);

        impuesto.setEditable(false);

        iva.setEditable(false);

        total.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleL, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nroFacturaL, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nroFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fechaActualL, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaActual)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conceptosL)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(costoImpresionL)
                                    .addComponent(montoBasicoL)
                                    .addComponent(subtotalL)
                                    .addComponent(impuestoL)
                                    .addComponent(IVAL)
                                    .addComponent(jLabel6))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(montoBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(costoImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(condicionTributariaL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(condicionTributaria, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(datosClienteL)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nroIDCatastralL)
                                        .addComponent(nombreClienteL)
                                        .addComponent(nroClienteL)
                                        .addComponent(domicilioFacturacionL))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                        .addComponent(nroIDCatastral)
                                        .addComponent(nombreCliente)
                                        .addComponent(domicilioFacturacion)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datosMedidorL)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaInstalacionL)
                                    .addComponent(nroMedidorL)
                                    .addComponent(marcaMedidorL))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(marcaMedidor, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(nroMedidor)
                                    .addComponent(fechaInstalacion))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fechaLecturaActualL)
                                .addGap(31, 31, 31)
                                .addComponent(fechaLecturaActual))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(diasLecturaL)
                                .addGap(69, 69, 69)
                                .addComponent(diasLectura))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fechaLecturaAnteriorL)
                                .addGap(18, 18, 18)
                                .addComponent(fechaLecturaAnterior))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(m3ConsumidosL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m3Consumidos, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(datosLecturaL)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(9, 9, 9))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nroFacturaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaActualL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addComponent(titleL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datosMedidorL)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marcaMedidorL)
                            .addComponent(marcaMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nroMedidorL)
                            .addComponent(nroMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaInstalacionL)
                            .addComponent(fechaInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datosLecturaL)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(datosClienteL)
                                    .addGap(19, 19, 19)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nroIDCatastralL)
                                        .addComponent(nroIDCatastral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nombreClienteL)
                                        .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nroClienteL))
                                    .addGap(4, 4, 4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(domicilioFacturacionL)
                                        .addComponent(domicilioFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fechaLecturaAnteriorL)
                                        .addComponent(fechaLecturaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fechaLecturaActualL)
                                        .addComponent(fechaLecturaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(diasLecturaL)
                                        .addComponent(diasLectura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(11, 11, 11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(m3ConsumidosL)
                                        .addComponent(m3Consumidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(condicionTributariaL)
                    .addComponent(condicionTributaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conceptosL)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(montoBasicoL)
                    .addComponent(montoBasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costoImpresionL)
                    .addComponent(costoImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotalL)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(impuestoL)
                    .addComponent(impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IVAL)
                    .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IVAL;
    private javax.swing.JLabel conceptosL;
    private javax.swing.JTextField condicionTributaria;
    private javax.swing.JLabel condicionTributariaL;
    private javax.swing.JTextField costoImpresion;
    private javax.swing.JLabel costoImpresionL;
    private javax.swing.JLabel datosClienteL;
    private javax.swing.JLabel datosLecturaL;
    private javax.swing.JLabel datosMedidorL;
    private javax.swing.JTextField diasLectura;
    private javax.swing.JLabel diasLecturaL;
    private javax.swing.JTextField domicilioFacturacion;
    private javax.swing.JLabel domicilioFacturacionL;
    private javax.swing.JTextField fechaActual;
    private javax.swing.JLabel fechaActualL;
    private javax.swing.JTextField fechaInstalacion;
    private javax.swing.JLabel fechaInstalacionL;
    private javax.swing.JTextField fechaLecturaActual;
    private javax.swing.JLabel fechaLecturaActualL;
    private javax.swing.JTextField fechaLecturaAnterior;
    private javax.swing.JLabel fechaLecturaAnteriorL;
    private javax.swing.JTextField impuesto;
    private javax.swing.JLabel impuestoL;
    private javax.swing.JTextField iva;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField m3Consumidos;
    private javax.swing.JLabel m3ConsumidosL;
    private javax.swing.JTextField marcaMedidor;
    private javax.swing.JLabel marcaMedidorL;
    private javax.swing.JTextField montoBasico;
    private javax.swing.JLabel montoBasicoL;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JLabel nombreClienteL;
    private javax.swing.JTextField nroCliente;
    private javax.swing.JLabel nroClienteL;
    private javax.swing.JTextField nroFactura;
    private javax.swing.JLabel nroFacturaL;
    private javax.swing.JTextField nroIDCatastral;
    private javax.swing.JLabel nroIDCatastralL;
    private javax.swing.JTextField nroMedidor;
    private javax.swing.JLabel nroMedidorL;
    private javax.swing.JTextField subtotal;
    private javax.swing.JLabel subtotalL;
    private javax.swing.JLabel titleL;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
